$num_compute_nodes = 2

Vagrant.configure("2") do |config|

  config.vm.box = "elastic/ubuntu-16.04-x86_64"
  config.ssh.keys_only = true

  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_address = '192.168.240.0/24'
  end

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
  config.vm.synced_folder "..", "/demo"

  config.vm.define "control" do |config|
    config.vm.hostname = "control"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.network "private_network", ip: "192.168.1.10"
    config.vm.provision "shell", path: "setup_control.sh", privileged: false
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 8
      libvirt.memory = 8192
    end
  end

  (1 .. $num_compute_nodes).each do |n|
    config.vm.define vm_name = "compute-#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.network "private_network", ip: "192.168.0.#{n+20}"
      config.vm.network "private_network", ip: "192.168.1.#{n+20}"
      config.vm.provision "shell", path: "setup_compute.sh", privileged: false
      config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 32
        libvirt.memory = 245760
        libvirt.storage :file, :size => '1000G'
        libvirt.storage :file, :size => '1000G'
      end
    end
  end

#  config.vm.define "onap" do |config|
#    config.vm.hostname = "onap"
#    config.vm.network "private_network", ip: "192.168.0.2"
#    config.vm.network "private_network", ip: "192.168.1.2"
#    config.vm.provision "shell", path: "create_onap.sh", privileged: false
#    config.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--memory", 4096]
#      vb.customize ["modifyvm", :id, "--cpus", 4]
#    end
#  end
end
