Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "puppet/scripts/bootstrap.sh"

  # ip configuration. Also, make sure this is in sync with puppet/hieradata/*
  node_ex_ip = "192.168.0.254"

  config.vm.provision "shell", path: "puppet/scripts/base1.sh"
  config.vm.provision "puppet" do |puppet|
      puppet.hiera_config_path = "puppet/hiera.yaml"
      puppet.working_directory = "/vagrant/puppet"
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
      puppet.manifest_file  = "base2.pp"
  end

  # During initial provisioning we expect yum update to get a new kernel. Because of that, we
  # will be required to reboot the vm. If you rather do that manually, simply comment out provision line below.
  # Otherwise, simply install the reload plugin in vagrant:  vagrant plugin install vagrant-reload
  config.vm.provision :reload

  config.vm.define "router-node" do |config|
    config.vm.box = "centos/6"
    config.vm.hostname = "router-node"
    config.vm.network "private_network", ip: "#{node_ex_ip}"
    config.vm.provider :libvirt do |libvirt|
      libvirt.management_network_address = '192.168.240.0/24'
      libvirt.memory = 1000
      libvirt.cpus = 1
    end
  end

end
